name: ooi
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - argcomplete=1.12.3
  - beautifulsoup4=4.10.0
  - bottleneck=1.3.2
  - chest=0.2.3
  - configobj=5.0.6
  - geos=3.9.1
  - gsw=3.4.0
  - hdf4=4.2.13
  - h5netcdf=0.11.0
  - jupyterlab=3.2.1
  - libnetcdf=4.6.2
  - matplotlib=3.4.3
  - munch>=2.1.0
  - netcdf4=1.4.2
  - nodejs=16.6.1
  - nose=1.3.7
  - numexpr=2.7.3
  - numpy=1.21.2
  - pip=21.2.2
  - pocean-core=1.9.3
  - pyasn1=0.4.8
  - pyaxiom=1.4.6
  - pygc=1.2.1
  - pyIGRF=0.3.3
  - pyncml=0.0.9
  - pytz=2021.3
  - pyYAML=6.0
  - scipy=1.7.1
  - simplejson=3.17.3
  - sockjs-tornado=1.0.6
  - tqdm=4.62.3
  - xarray=0.19.0
  - xlrd=2.0.1
  - yaml=0.2.5
  - pip:
    - https://bitbucket.org/ooicgsn/pyseas/get/develop.zip
    - https://bitbucket.org/ooicgsn/cgsn-parsers/get/master.zip
    - https://bitbucket.org/ooicgsn/cgsn-processing/get/master.zip
